implent mask instead of np.where() and warning suppression
PhasesResearchLab/dfttk pull request #124
Opened 2024-09-25 22:27 UTC by lukeamyers

Apparently, the correct solution is to use a mask. Now it won't give warnings for log(0)

2024-09-25 22:28 UTC, lukeamyers commented
Could you test this? I only work with those lines of the code.

2024-09-26 01:43 UTC, nhew1994 requested changes

2024-09-26 01:43 UTC, nhew1994 commented on dfttk/thermal_electronic.py
> +        mask = (fermi_dist = 0) or (fermi_dist = 1)
It works if you do this:
```
mask = (fermi_dist == 0) | (fermi_dist == 1)
```

2024-09-26 01:48 UTC, nhew1994 commented
TODO: similar changes for Cv_el

2024-09-26 15:06 UTC, nhew1994 approved these changes

2024-09-26 15:07 UTC, merged